# Generated by Django 4.0 on 2021-12-14 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('body', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='authentication.user')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.PositiveSmallIntegerField(default=0)),
                ('like_published', models.DateTimeField(auto_now_add=True)),
                ('like_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_post', to='post.post')),
                ('like_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislike', models.PositiveSmallIntegerField(default=0)),
                ('dislike_published', models.DateTimeField(auto_now_add=True)),
                ('dislike_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike_post', to='post.post')),
                ('dislike_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike_user', to='authentication.user')),
            ],
        ),
    ]
